windows:
  runs-on: windows-latest
  name: "windows"

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

    steps:
      - name: Set up Perl
        run: |
          choco install strawberryperl
          echo "##[add-path]C:\strawberry\c\bin;C:\strawberry\perl\site\bin;C:\strawberry\perl\bin"

      - name: perl -V
        run: perl -V

      - uses: actions/checkout@v2
      - name: "install-with-cpm"

        uses: perl-actions/install-with-cpm@stable
        with:
          install: |
            abbreviation
            ACH
      # checking that both modules are installed
      - run: perl -Mabbreviation -e1
      - run: perl -MACH -e1