# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      - name: install with cpm
        # You may pin to the exact commit or the version.
        # uses: perl-actions/install-with-cpm@7dead49a9920a1f07629c1902f1fe19c56b6ff12
        uses: perl-actions/install-with-cpm@v1.3
        with:
          # List of modules or distributions to install [seperated by newline]
          install: # optional
          # Use a cpanfile to install modules
          cpanfile: cpanfile
          # Run or not the unit tests
          tests: # optional
          # Perform a global or local installation: -g
          global: # optional, default is true
          # Extra args used passed to install command
          args: # optional
          # Perform installations as root
          sudo: # optional, default is true
          # Path of perl to use default to currtent PATH
          perl: # optional, default is perl
          # Path where to install cpm: the string can use $Config values
          path: # optional, default is $Config{installsitescript}/cpm
          # Which version to install
          version: # optional, default is master      

      # Runs a single command using the runners shell
      - name: Run a one-line script
        run: echo Hello, world!

      # Runs a set of commands using the runners shell
      - name: Run a multi-line script
        run: |
          echo Add other actions to build,
          echo test, and deploy your project.


